// flow-typed signature: 948d2ec32fdadf80419e0817e900fa17
// flow-typed version: <<STUB>>/redom_v^1.17.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redom/dist/prism' {
  declare module.exports: any;
}

declare module 'redom/dist/redom.es' {
  declare module.exports: any;
}

declare module 'redom/dist/redom' {
  declare module.exports: any;
}

declare module 'redom/dist/redom.min' {
  declare module.exports: any;
}

declare module 'redom/rollup.config' {
  declare module.exports: any;
}

declare module 'redom/src/create-element' {
  declare module.exports: any;
}

declare module 'redom/src/html' {
  declare module.exports: any;
}

declare module 'redom/src/index' {
  declare module.exports: any;
}

declare module 'redom/src/list' {
  declare module.exports: any;
}

declare module 'redom/src/mount' {
  declare module.exports: any;
}

declare module 'redom/src/router' {
  declare module.exports: any;
}

declare module 'redom/src/setattr' {
  declare module.exports: any;
}

declare module 'redom/src/setchildren' {
  declare module.exports: any;
}

declare module 'redom/src/setstyle' {
  declare module.exports: any;
}

declare module 'redom/src/svg' {
  declare module.exports: any;
}

declare module 'redom/src/text' {
  declare module.exports: any;
}

declare module 'redom/src/util' {
  declare module.exports: any;
}

declare module 'redom/test/index' {
  declare module.exports: any;
}

declare module 'redom/test/redom' {
  declare module.exports: any;
}

declare module 'redom/test/test' {
  declare module.exports: any;
}

declare module 'redom/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redom/dist/prism.js' {
  declare module.exports: $Exports<'redom/dist/prism'>;
}
declare module 'redom/dist/redom.es.js' {
  declare module.exports: $Exports<'redom/dist/redom.es'>;
}
declare module 'redom/dist/redom.js' {
  declare module.exports: $Exports<'redom/dist/redom'>;
}
declare module 'redom/dist/redom.min.js' {
  declare module.exports: $Exports<'redom/dist/redom.min'>;
}
declare module 'redom/rollup.config.js' {
  declare module.exports: $Exports<'redom/rollup.config'>;
}
declare module 'redom/src/create-element.js' {
  declare module.exports: $Exports<'redom/src/create-element'>;
}
declare module 'redom/src/html.js' {
  declare module.exports: $Exports<'redom/src/html'>;
}
declare module 'redom/src/index.js' {
  declare module.exports: $Exports<'redom/src/index'>;
}
declare module 'redom/src/list.js' {
  declare module.exports: $Exports<'redom/src/list'>;
}
declare module 'redom/src/mount.js' {
  declare module.exports: $Exports<'redom/src/mount'>;
}
declare module 'redom/src/router.js' {
  declare module.exports: $Exports<'redom/src/router'>;
}
declare module 'redom/src/setattr.js' {
  declare module.exports: $Exports<'redom/src/setattr'>;
}
declare module 'redom/src/setchildren.js' {
  declare module.exports: $Exports<'redom/src/setchildren'>;
}
declare module 'redom/src/setstyle.js' {
  declare module.exports: $Exports<'redom/src/setstyle'>;
}
declare module 'redom/src/svg.js' {
  declare module.exports: $Exports<'redom/src/svg'>;
}
declare module 'redom/src/text.js' {
  declare module.exports: $Exports<'redom/src/text'>;
}
declare module 'redom/src/util.js' {
  declare module.exports: $Exports<'redom/src/util'>;
}
declare module 'redom/test/index.js' {
  declare module.exports: $Exports<'redom/test/index'>;
}
declare module 'redom/test/redom.js' {
  declare module.exports: $Exports<'redom/test/redom'>;
}
declare module 'redom/test/test.js' {
  declare module.exports: $Exports<'redom/test/test'>;
}
declare module 'redom/watch.js' {
  declare module.exports: $Exports<'redom/watch'>;
}
